In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [34]:
!ls

Untitled.ipynb                flight_vertical_2.csv
custom_uav1_scenario2.csv     flight_vertical_2_labeled.csv
custom_uav2_scenario2.csv     flight_vertical_3.csv
dataLabeling.m                flight_vertical_3_labeled.csv
flight_vertical_1.csv         myupdatefcn.m
flight_vertical_1_labeled.csv test.csv

In [22]:
unlabeled_data = pd.read_csv('flight_vertical_3.csv')
unlabeled_data.shape

(11763, 13)

In [23]:
unlabeled_data.head()

,time,x,y,z,roll,pitch,yaw,xv,yv,zv,rollv,pitchv,yawv
0,1.556060e+09,0.000629,-0.015383,-0.005831,-0.013535,-0.015279,-0.098218,-0.000671,0.000489,0.000773,0.001388,0.003989,-0.002493
1,1.556060e+09,0.000652,-0.015383,-0.005815,-0.013728,-0.015454,-0.097904,0.000278,-0.000002,0.000188,-0.002332,-0.002124,0.003797
2,1.556060e+09,0.000622,-0.015371,-0.005773,-0.013965,-0.015313,-0.098039,-0.000349,0.000143,0.000499,-0.002829,0.001677,-0.001604
3,1.556060e+09,0.000543,-0.015236,-0.005777,-0.013295,-0.014815,-0.098108,-0.000944,0.001610,-0.000051,0.008002,0.005947,-0.000831
4,1.556060e+09,0.000358,-0.015306,-0.005799,-0.013879,-0.013838,-0.098013,-0.002229,-0.000830,-0.000255,-0.007010,0.011738,0.001139

In [24]:
labeled_data = pd.read_csv('flight_vertical_3_labeled.csv')
labeled_data.shape

(11763, 5)

In [25]:
labeled_data.head()

          z        xv        yv        zv  label
0 -0.005830 -0.000671  0.000489  0.000773      1
1 -0.005815  0.000278 -0.000002  0.000188      1
2 -0.005773 -0.000349  0.000143  0.000499      1
3 -0.005777 -0.000944  0.001610 -0.000051      1
4 -0.005799 -0.002230 -0.000830 -0.000255      1

In [26]:
labeled_data = labeled_data.drop(columns=['z','xv','yv','zv'])
pd.unique(labeled_data['label'])

array([1, 2, 3, 4, 5])

In [27]:
labeled_data = labeled_data.replace({1:'Hold',2:'Takeoff',3:'Hover',4:'Search',5:'Land'})
labeled_data.head()

  label
0  Hold
1  Hold
2  Hold
3  Hold
4  Hold

In [28]:
cat_data = pd.concat([unlabeled_data,labeled_data],axis=1)
cat_data = cat_data.rename(columns={'xv':'x_v','yv':'y_v','zv':'z_v','rollv':'roll_v','pitchv':'pitch_v','yawv':'yaw_v'})

In [29]:
cat_data.head()

,time,x,y,z,roll,pitch,yaw,x_v,y_v,z_v,roll_v,pitch_v,yaw_v,label
0,1.556060e+09,0.000629,-0.015383,-0.005831,-0.013535,-0.015279,-0.098218,-0.000671,0.000489,0.000773,0.001388,0.003989,-0.002493,Hold
1,1.556060e+09,0.000652,-0.015383,-0.005815,-0.013728,-0.015454,-0.097904,0.000278,-0.000002,0.000188,-0.002332,-0.002124,0.003797,Hold
2,1.556060e+09,0.000622,-0.015371,-0.005773,-0.013965,-0.015313,-0.098039,-0.000349,0.000143,0.000499,-0.002829,0.001677,-0.001604,Hold
3,1.556060e+09,0.000543,-0.015236,-0.005777,-0.013295,-0.014815,-0.098108,-0.000944,0.001610,-0.000051,0.008002,0.005947,-0.000831,Hold
4,1.556060e+09,0.000358,-0.015306,-0.005799,-0.013879,-0.013838,-0.098013,-0.002229,-0.000830,-0.000255,-0.007010,0.011738,0.001139,Hold

In [30]:
d = {'label':cat_data['label'],
     'pitch':cat_data['pitch'],
     'pitch_v':cat_data['pitch_v'],
     'roll':cat_data['roll'],
     'roll_v':cat_data['roll_v'],
     'time':cat_data['time'],
     'x':cat_data['x'],
     'x_v':cat_data['x_v'],
     'y':cat_data['y'], 
     'y_v':cat_data['y_v'],
     'yaw':cat_data['yaw'],
     'yaw_v':cat_data['yaw_v'],
     'z':cat_data['z'],
     'z_v':cat_data['z_v']}
df = pd.DataFrame(data=d)
df.to_csv('test.csv',index=False)

In [31]:
data = pd.read_csv('test.csv')
data.head()

,label,pitch,pitch_v,roll,roll_v,time,x,x_v,y,y_v,yaw,yaw_v,z,z_v
0,Hold,-0.015279,0.003989,-0.013535,0.001388,1.556060e+09,0.000629,-0.000671,-0.015383,0.000489,-0.098218,-0.002493,-0.005831,0.000773
1,Hold,-0.015454,-0.002124,-0.013728,-0.002332,1.556060e+09,0.000652,0.000278,-0.015383,-0.000002,-0.097904,0.003797,-0.005815,0.000188
2,Hold,-0.015314,0.001677,-0.013965,-0.002829,1.556060e+09,0.000622,-0.000349,-0.015371,0.000143,-0.098039,-0.001604,-0.005773,0.000499
3,Hold,-0.014815,0.005947,-0.013295,0.008002,1.556060e+09,0.000543,-0.000944,-0.015236,0.001610,-0.098108,-0.000831,-0.005777,-0.000051
4,Hold,-0.013838,0.011738,-0.013879,-0.007010,1.556060e+09,0.000358,-0.002229,-0.015305,-0.000830,-0.098013,0.001139,-0.005799,-0.000255

In [32]:
X_train = data.drop(columns=['label', 'time','x','y','pitch_v','roll_v','yaw_v'])
print(X_train.head())

      pitch      roll       x_v       y_v       yaw         z       z_v
0 -0.015279 -0.013535 -0.000671  0.000489 -0.098218 -0.005831  0.000773
1 -0.015454 -0.013728  0.000278 -0.000002 -0.097904 -0.005815  0.000188
2 -0.015314 -0.013965 -0.000349  0.000143 -0.098039 -0.005773  0.000499
3 -0.014815 -0.013295 -0.000944  0.001610 -0.098108 -0.005777 -0.000051
4 -0.013838 -0.013879 -0.002229 -0.000830 -0.098013 -0.005799 -0.000255

In [33]:
df.to_csv('custom_uav2_scenario2.csv',index=False)